version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - data_volume:/var/lib/mysql
    networks:
      - inception_network
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: imroot
      WP_DB_NAME: wordpress
      WP_DB_USER: pcunha
      WP_DB_PASSWORD: pcc
  wordpress:
    image: wordpress
    depends_on:
      - mariadb
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    volumes:
      - site_volume:/var/www/html
    networks:
      - inception_network
    environment:
      DOMAIN_NAME: pcunha
      MYSQL_HOST: mariadb
      WP_DB_NAME: wordpress
      WP_DB_USER: pcunha
      WP_DB_PASSWORD: pcc
      WP_USER: pcunha_wp
      WP_PASSWORD: pcunha_wp
  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    build: requirements/nginx
      #restart: no
    volumes:
      - site_volume:/var/www/html
    networks:
      - inception_network
    ports:
      - "443:443"

volumes:
  data_volume:
  site_volume:

networks:
  inception_network:
    driver: bridge
