#!/usr/bin/bash

vim -p Makefile ./srcs/docker-compose.yml \
	./srcs/requirements/wordpress/Dockerfile\
	./srcs/requirements/wordpress/tools/install_wordpress.sh\
	./srcs/requirements/wordpress/conf/setup_wordpress.sh\
	./srcs/requirements/mariadb/Dockerfile\
	./srcs/requirements/mariadb/tools/install_mariadb.sh\
	./srcs/requirements/mariadb/conf/setup_mariadb.sh\
	./srcs/requirements/nginx/Dockerfile\
	./srcs/requirements/nginx/tools/install_nginx.sh\
	./srcs/requirements/nginx/conf/setup_nginx.sh\
	./srcs/requirements/nginx/conf/nginx.conf\
