#!/bin/bash
FILE=/etc/hosts
SITE=pcunha.42.fr

# coloca
sudo chmod 666 /etc/hosts
#if grep -E $SITE $FILE
#then
#	echo "Tirando host ..."
#	sudo sed -i "" "/$SITE/d" /etc/hosts
#	echo "ok"
#fi
echo "$(grep -v $SITE $FILE)" > $FILE
sudo chmod 644 /etc/hosts
